// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestsqaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testsqa() {
    driver.get("https://www.demoblaze.com/index.html");
    driver.manage().window().setSize(new Dimension(1155, 700));
    driver.findElement(By.id("nava")).click();
    driver.findElement(By.id("itemc")).click();
    driver.findElement(By.id("narvbarx")).click();
    driver.findElement(By.linkText("Samsung galaxy s6")).click();
    driver.findElement(By.cssSelector(".item > img")).click();
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.cssSelector(".price-container")).click();
    driver.findElement(By.cssSelector("strong")).click();
    driver.findElement(By.cssSelector("#more-information > p")).click();
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    driver.findElement(By.linkText("Laptops")).click();
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(6) .card-img-top")).click();
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.cssSelector(".item > img")).click();
    driver.findElement(By.cssSelector(".price-container")).click();
    driver.findElement(By.id("more-information")).click();
    driver.findElement(By.id("more-information")).click();
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    driver.findElement(By.linkText("Monitors")).click();
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(1) .card-block")).click();
    driver.findElement(By.linkText("Apple monitor 24")).click();
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    driver.findElement(By.id("prev2")).click();
    driver.findElement(By.id("next2")).click();
    driver.findElement(By.cssSelector(".col-sm-3 b")).click();
    driver.findElement(By.cssSelector(".col-sm-3 p:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".caption > p:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".caption > p:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".caption > p:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".col-sm-4 p")).click();
    driver.findElement(By.cssSelector(".col-sm-4 b")).click();
    driver.findElement(By.cssSelector(".m-0")).click();
    driver.findElement(By.cssSelector(".m-0")).click();
    {
      WebElement element = driver.findElement(By.id("fotcont"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("fotcont"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("fotcont"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("fotcont")).click();
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.cssSelector("#exampleModal span")).click();
    driver.findElement(By.linkText("About us")).click();
    driver.findElement(By.cssSelector("#videoModal .modal-header")).click();
    driver.findElement(By.cssSelector("#videoModal .modal-header span")).click();
    driver.findElement(By.id("cartur")).click();
    driver.findElement(By.id("login2")).click();
    driver.findElement(By.cssSelector("#logInModal span")).click();
    driver.findElement(By.id("signin2")).click();
    driver.findElement(By.cssSelector("#signInModal span")).click();
  }
}
